#!/usr/bin/env python3
"""Install git pre-push hook to enforce L3 gate approval."""

from __future__ import annotations

import argparse
import stat
import subprocess
from pathlib import Path


def run_git(repo: Path, args: list[str]) -> tuple[int, str, str]:
    proc = subprocess.run(["git", "-C", str(repo), *args], text=True, capture_output=True)
    return proc.returncode, proc.stdout.strip(), proc.stderr.strip()


def to_sh_path(path: Path) -> str:
    return path.resolve().as_posix()


def main() -> int:
    parser = argparse.ArgumentParser(description="Install pre-push hook for TRIAD L3 gate enforcement.")
    parser.add_argument("--repo", required=True, help="Target repository where hook will be installed.")
    parser.add_argument(
        "--hooks-dir",
        default=".githooks",
        help="Hooks directory relative to target repository (default: .githooks).",
    )
    parser.add_argument(
        "--python-cmd",
        default="python",
        help="Python command used by hook (default: python).",
    )
    parser.add_argument(
        "--strict-missing-change-package",
        action="store_true",
        help="Configure hook to fail when no Change Package exists.",
    )
    args = parser.parse_args()

    target_repo = Path(args.repo).resolve()
    if not target_repo.exists():
        raise FileNotFoundError(f"Repository path not found: {target_repo}")

    rc, out, err = run_git(target_repo, ["rev-parse", "--is-inside-work-tree"])
    if rc != 0 or out.lower() != "true":
        msg = err or out or "Not a git repository."
        raise RuntimeError(f"Cannot install hook: {msg}")

    tools_dir = Path(__file__).resolve().parent
    guard_script = tools_dir / "l3_pre_push_guard.py"
    if not guard_script.exists():
        raise FileNotFoundError(f"Guard script not found: {guard_script}")

    hooks_dir = (target_repo / args.hooks_dir).resolve()
    hooks_dir.mkdir(parents=True, exist_ok=True)
    hook_path = hooks_dir / "pre-push"

    strict_flag = " --strict-missing-change-package" if args.strict_missing_change_package else ""
    hook_text = (
        "#!/usr/bin/env sh\n"
        "# Auto-generated by tools/install_pre_push_hook.py\n"
        f'PY_CMD="${{TRIAD_PYTHON:-{args.python_cmd}}}"\n'
        f'REPO_PATH="{to_sh_path(target_repo)}"\n'
        f'GUARD_PATH="{to_sh_path(guard_script)}"\n'
        '"$PY_CMD" "$GUARD_PATH" --repo "$REPO_PATH"' + strict_flag + "\n"
        "exit $?\n"
    )
    hook_path.write_text(hook_text, encoding="utf-8")

    current_mode = hook_path.stat().st_mode
    hook_path.chmod(current_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    rc, _, err = run_git(target_repo, ["config", "core.hooksPath", args.hooks_dir])
    if rc != 0:
        raise RuntimeError(f"Failed to set core.hooksPath: {err}")

    print(f"Hook installed: {hook_path}")
    print(f"core.hooksPath set to: {args.hooks_dir}")
    print("To bypass once (not recommended): git push --no-verify")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
